name: CI Jobs
on: 
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
jobs:
  build-and-test:
    strategy:
      matrix:
        go-version: [1.23.x]
        os: [ubuntu-24.04, windows-2025]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
      with:
       fetch-depth: 0
    - name: Install Go 
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: "build and unit-test Linux"
      if: runner.os == 'Linux'
      run:  ./build.sh test createBuildZip
    - name: "build and unit-test Windows"
      if: runner.os == 'Windows'
      run:  ./build.bat test createBuildZip      
    - name: Publish Unit Test Results for Linux
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always() && runner.os == 'Linux'
      with:
        files: logs/TestsResult.xml    
    - name: Publish Unit Test Results for Windows
      uses: EnricoMi/publish-unit-test-result-action/windows@v2
      if: always() && runner.os == 'Windows'
      with:
        files: logs/TestsResult.xml            
    - name: "Integration Tests on Linux"
      if: runner.os == 'Linux'
      run:  ./build/IntegrationTests.sh        
    - name: 'Upload Artifact logs'
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Logs-${{ matrix.os }}.txt
        path: logs/*
        retention-days: 1                
    - name: 'Upload Artifact gpsa linux binary'
      uses: actions/upload-artifact@v4
      with:
        name: gpsa-${{ matrix.os }}
        path: bin/gpsa
        retention-days: 1
    - name: 'Upload Artifact gpsa windows binary'
      uses: actions/upload-artifact@v4
      with:
        name: gpsa-${{ matrix.os }}
        path: bin/gpsa.exe
        retention-days: 1        
    - name: 'Upload Artifact Version.txt'
      uses: actions/upload-artifact@v4
      with:
        name: Version-${{ matrix.os }}.txt
        path: logs/Version.txt
        retention-days: 1      
    - name: 'Upload Artifact linux_bin.zip'
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v4
      with:
        name: linux_bin.zip
        path: linux_bin.zip
        retention-days: 1        
    - name: 'Upload Artifact linux_Build.zip'
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v4
      with:
        name: linux_Build.zip
        path: linux_Build.zip
        retention-days: 1              
    - name: 'Upload Artifact windows_bin.zip'
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: windows_bin.zip
        path: windows_bin.zip
        retention-days: 1        
    - name: 'Upload Artifact windows_Build.zip'
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: windows_Build.zip
        path: windows_Build.zip
        retention-days: 1   
