name: CI Jobs
on: 
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
jobs:
  build-unit_test:
    strategy:
      matrix:
        go-version: [1.23.x]
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
      with:
       fetch-depth: 0
    - name: Install Go 
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: "build and unit-test"
      env:
        GITHUB_RUNNER_OS:  ${{ matrix.os }}
      run:  ./build.sh test createBuildZip
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        junit_files: logs/TestsResult.xml       
    - name: 'Upload Artifact gpsa binary'
      uses: actions/upload-artifact@v4
      with:
        name: gpsa-${{ matrix.os }}
        path: bin/gpsa
        retention-days: 1
    - name: 'Upload Artifact Version.txt'
      uses: actions/upload-artifact@v4
      with:
        name: Version-${{ matrix.os }}.txt
        path: logs/Version.txt
        retention-days: 1    
    - name: 'Upload Artifact logs'
      uses: actions/upload-artifact@v4
      with:
        name: Logs-${{ matrix.os }}.txt
        path: logs/*
        retention-days: 1                     
